# Generated by Django 4.0.3 on 2022-06-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departmentt',
            new_name='Department',
        ),
    ]
